#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <vector>
#include <Poseidon/Asset/Formats/P3D/MLODLoader.hpp>
#include <Poseidon/World/Model/Model.hpp>
#include "../../../test_fixtures.hpp"
#include <string>
#include <vector>

using namespace Poseidon::Model;

// fuzz_p3d regression: an SP3X element count must be rejected before it drives a
// huge allocation. "MLOD" v1.0 / 1 LOD, then an SP3X header with nPos = 0x7FFFFFFF.
// Pre-fix readVertexTable did points.reserve(nPos) (~32GB); validateCount now throws.
TEST_CASE("MLODLoader: malformed vertex count is rejected before allocation", "[mlod][loader][fuzz]")
{
    std::vector<char> buf;
    auto put32 = [&](uint32_t v)
    {
        for (int i = 0; i < 4; ++i)
            buf.push_back(static_cast<char>((v >> (8 * i)) & 0xFF));
    };
    buf.push_back('M');
    buf.push_back('L');
    buf.push_back('O');
    buf.push_back('D');
    buf.push_back(1);
    buf.push_back(0); // versionMajor.minor
    buf.push_back(0);
    buf.push_back(0); // padding
    put32(1);         // lodCount
    buf.push_back('S');
    buf.push_back('P');
    buf.push_back('3');
    buf.push_back('X');
    put32(28);         // headSize (no bytes beyond the 28-byte struct)
    put32(0);          // version
    put32(0x7FFFFFFF); // nPos
    put32(0);          // nNorm
    put32(0);          // nFace
    put32(0);          // flags

    REQUIRE_THROWS_WITH(
        Poseidon::Asset::Formats::MLODLoader::loadFromBuffer(buf.data(), static_cast<int>(buf.size()), "fuzz"),
        Catch::Matchers::ContainsSubstring("count"));
}

TEST_CASE("MLODLoader: Basic loading - complex_vehicle_mlod.p3d", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));

    // Compile to compute missing data
    REQUIRE(model.compile());

    // Basic model metadata
    REQUIRE(model.sourceFormat == "MLOD");
    REQUIRE(model.sourceVersion == 11); // 1.1
    REQUIRE(model.sourcePath == GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));

    // LOD count
    REQUIRE(model.lodLevels.size() == 3);

    // Model should be compiled
    REQUIRE(model.isCompiled());
}

TEST_CASE("MLODLoader: Geometry data", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    REQUIRE(model.lodLevels.size() > 0);

    const auto& lod0 = model.lodLevels[0];
    const auto& mesh = lod0.mesh;

    // Check vertex count (MLOD expands differently than old loader)
    // MLOD stores compact vertices (point table + per-face normals/UVs)
    // Old loader merges more aggressively during expansion
    // Note: Investigate if further merging is needed or if difference is acceptable
    REQUIRE(mesh.vertices.size() >= 11);

    // Check face count (triangles + quads, should match old loader)
    int totalFaces = static_cast<int>(mesh.triangles.size() + mesh.quads.size());
    REQUIRE(totalFaces >= 4);

    // Verify some vertices have valid positions
    REQUIRE(mesh.vertices[0].position.x != 0.0f);
    REQUIRE(mesh.vertices[0].position.y != 0.0f);
    REQUIRE(mesh.vertices[0].position.z != 0.0f);

    // Verify triangles have valid indices
    REQUIRE(mesh.triangles[0].indices[0] < mesh.vertices.size());
    REQUIRE(mesh.triangles[0].indices[1] < mesh.vertices.size());
    REQUIRE(mesh.triangles[0].indices[2] < mesh.vertices.size());
}

TEST_CASE("MLODLoader: Materials", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // Should have materials
    REQUIRE(mesh.materials.size() > 0);

    // Materials should have names
    for (const auto& mat : mesh.materials)
    {
        REQUIRE_FALSE(mat.name.empty());
    }
}

TEST_CASE("MLODLoader: Sections (generated)", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // Sections should be generated by compile()
    REQUIRE(mesh.sections.size() > 0);

    // Sections should have valid data
    for (const auto& section : mesh.sections)
    {
        REQUIRE(section.triangleCount > 0);
    }
}

TEST_CASE("MLODLoader: Selections", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // Should have selections
    REQUIRE(mesh.selections.size() > 0);

    bool hasNonEmptySelection = false;
    for (const auto& sel : mesh.selections)
        hasNonEmptySelection = hasNonEmptySelection || !sel.name.empty();
    REQUIRE(hasNonEmptySelection);
}

TEST_CASE("MLODLoader: Properties", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // MLOD files may have properties from TAGG #Property# tags
    // Check if properties exist (may be empty, that's OK)
    REQUIRE(mesh.properties.size() >= 0);
}

TEST_CASE("MLODLoader: Proxies (generated)", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // The synthetic fixture has no proxy selections; compile should preserve a
    // valid empty proxy list.
    REQUIRE(mesh.proxies.empty());
}

TEST_CASE("MLODLoader: Bounding volumes", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    const auto& mesh = model.lodLevels[0].mesh;

    // Bounding box should be computed by compile()
    REQUIRE(mesh.boundingBox.min.x < mesh.boundingBox.max.x);
    REQUIRE(mesh.boundingBox.min.y < mesh.boundingBox.max.y);
    REQUIRE(mesh.boundingBox.min.z < mesh.boundingBox.max.z);

    // Bounding sphere should be computed by compile()
    REQUIRE(mesh.boundingSphere.radius > 0.0f);
}

TEST_CASE("MLODLoader: Multiple LODs", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    REQUIRE(model.lodLevels.size() == 3);

    // LOD 0 should have the most detail
    REQUIRE(model.lodLevels[0].mesh.vertices.size() > 0);
    REQUIRE(model.lodLevels[0].mesh.triangles.size() > 0);

    // Some LODs may be empty (special LODs like hitpoints)
    // Just verify structure is valid
    for (const auto& lod : model.lodLevels)
    {
        REQUIRE(lod.resolution >= 0.0f);
    }
}

TEST_CASE("MLODLoader: Resolution values", "[mlod][loader]")
{
    auto model = Poseidon::Asset::Formats::MLODLoader::load(GET_FIXTURE("mlod/complex_vehicle_mlod.p3d"));
    model.compile();

    // Check that LODs have resolution values
    REQUIRE(model.lodLevels.size() > 0);

    // LOD 0 should have highest resolution (lowest numeric value for view distance)
    REQUIRE(model.lodLevels[0].resolution >= 0.0f);
}
