#pragma once

// UIActionType enum, extracted so it can be included anywhere (AI/World/UI use it
// by value) without pulling the full UiActions.hpp / Game layer.

#include <Poseidon/Foundation/Types/EnumDecl.hpp>

DECL_ENUM(UIActionType)
DEFINE_ENUM_BEG(UIActionType)
	ATNone,
	ATGetInCommander,
	ATGetInDriver,
	ATGetInGunner,
	ATGetInCargo,
	ATHeal,
	ATRepair,
	ATRefuel,
	ATRearm,
	ATGetOut,
	ATLightOn,
	ATLightOff,
	ATEngineOn,
	ATEngineOff,
	ATSwitchWeapon,
	ATUseWeapon,
	ATLoadMagazine,
	ATTakeWeapon,
	ATTakeMagazine,
	ATTakeFlag,
	ATReturnFlag,
	ATTurnIn,
	ATTurnOut,
	ATWeaponInHand,
	ATWeaponOnBack,
	ATSitDown, // usable in safe mode
	ATLand,
	ATCancelLand,
	ATEject,
	ATMoveToDriver,
	ATMoveToGunner,
	ATMoveToCommander,
	ATMoveToCargo,
	ATHideBody,
	ATTouchOff,
	ATSetTimer,
	ATDeactivate,
	ATNVGoggles,
	ATManualFire,
	ATAutoHover,
	ATStrokeFist,
	ATStrokeGun,
	ATLadderUp,
	ATLadderDown,
	ATLadderOnDown,
	ATLadderOnUp,
	ATLadderOff,
	ATFireInflame,
	ATFirePutDown,
	ATLandGear,
	ATFlapsDown,
	ATFlapsUp,
	ATSalute,
	ATScudLaunch,
	ATScudStart,
	ATUser,
	ATDropWeapon,
	ATDropMagazine,
	ATUserType,
	ATHandGunOn,
	ATHandGunOff,
	ATTakeMine,
	ATDeactivateMine,
	ATUseMagazine,
DEFINE_ENUM_END(UIActionType)
